### ISSUE TITLE
teleoperation from keyboard on the game window doesn't work

### ISSUE THREAD

**Issue by mhallak** [DynoRobotics/unity_ros2#7]
Ubuntu 18.04 
ROS2 Dashing 
Unity3d 2019.2.9f1 Personal

I am echoing /cmd_vel as you recommended:` ros2 topic echo /cmd_vel`
I am playing the scene: no errors, everything is smooth.
I try to move the turtlebot with all the keyboard keys without any success.
When I am publishing some values on the topic via ros2 topic pub command, then the turtlebot moves fine.
Any hint?
I attached a screen of my environment so that may be something will be very clear to you.
![Screenshot from 2019-10-27 17-34-46](https://user-images.githubusercontent.com/2555633/67637159-4aa1ef00-f8e0-11e9-9acd-fd5d2791cf24.png)

**Comment by samiamlabs** [comment]
I think the teleop script is deactivated because something is wrong with the Unity Input System on Windows that makes it move the robot then the Game windows is selected.

You should be able to activate the script under RosInterface in the Unity Scene. Publishing to `cmd_vel` in a terminal and sending navigation goals should also work.

We will update the outdated readthedocs tutorial soon.

**Comment by mhallak** [comment]
It works. The cause is that I didn't realise that the script "Unity Input Teleop Script" was not checked....
(In the Unity3d Editor). 
Embarrassed and ashamed,
Sorry
